---
- include: redhat-handlers.yml
  when: ansible_os_family == 'RedHat'

- include: debian-handlers.yml
  when: ansible_os_family == 'Debian'

- name: Restart PostgreSQL systemd service
  systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted
